import json


def read_json_file(file_path):
    with open(file_path, "r") as f:
        data = json.load(f)
    return data


def read_file(file_path):
    with open(file_path, "r") as file:
        content = file.read()
        return content



def Singleton(cls):
    """
        Decorates a class as a singleton class. This was generated by chatgpt
    """
    instances = {}

    def get_instance(*args, **kwargs):
        if cls not in instances:
            instances[cls] = cls(*args, **kwargs)
        return instances[cls]

    return get_instance